// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: keywords.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RES {

  /// <summary>Holder for reflection information generated from keywords.proto</summary>
  public static partial class KeywordsReflection {

    #region Descriptor
    /// <summary>File descriptor for keywords.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KeywordsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5rZXl3b3Jkcy5wcm90bxIDUkVTGgx0c3YycGIucHJvdG8icAoJUmVzUmV3",
            "YXJkEhoKBndlaWdodBgBIAEoBUIKivEEBuadg+mHjRInCgR0eXBlGAIgASgO",
            "Mg0uUkVTLkl0ZW1UeXBlQgqK8QQG57G75Z6LEh4KCnByb3BvcnRpb24YAyAB",
            "KAVCCorxBAbmr5TkvosqiQIKCEl0ZW1UeXBlEhQKEEl0ZW1UeXBlX2ludmFs",
            "aWQQABIdCg1JdGVtVHlwZV9jb2luEAEaCorTDgbpkp7npagSIAoQSXRlbVR5",
            "cGVfZGlhbW9uZBACGgqK0w4G6ZK755+zEhwKDEl0ZW1UeXBlX2V4cBADGgqK",
            "0w4G57uP6aqMEh8KD0l0ZW1UeXBlX2VuZW5yeRAEGgqK0w4G5L2T5YqbEi0K",
            "Gkl0ZW1UeXBlX2FjaGlldmVtZW50X3BvaW50EAUaDYrTDgnmiJDlsLHngrkS",
            "GgoNSXRlbVR5cGVfZmlzaBAGGgeK0w4D6bG8EhwKD0l0ZW1UeXBlX2Zsb3dl",
            "chAHGgeK0w4D6IqxKuIJCg5VbmxvY2tGdW5jdGlvbhIaChZVbmxvY2tGdW5j",
            "dGlvbl9JbnZhbGlkEAASIwoTVW5sb2NrRnVuY3Rpb25fVGFzaxABGgqK0w4G",
            "5Lu75YqhEjAKGlVubG9ja0Z1bmN0aW9uX0ZyZWVEaWFtb25kEAIaEIrTDgzl",
            "hY3otLnpkrvnn7MSLAoWVW5sb2NrRnVuY3Rpb25fRnJlZUJveBADGhCK0w4M",
            "5YWN6LS55a6d566xEi0KF1VubG9ja0Z1bmN0aW9uX0ZyZWVHaWZ0EAQaEIrT",
            "DgzlhY3otLnnpLzljIUSMAoaVW5sb2NrRnVuY3Rpb25fUmVtb3ZlQ2xlcmsQ",
            "BRoQitMODOaSpOS4i+WRmOW3pRIpChZVbmxvY2tGdW5jdGlvbl9XZWFrVGlw",
            "EAYaDYrTDgnlsI/liqnmiYsSKQoWVW5sb2NrRnVuY3Rpb25fVmlwR2FtZRAH",
            "Gg2K0w4J5bCP5ri45oiPEjQKGFVubG9ja0Z1bmN0aW9uX0F1dG9HdWVzdBAI",
            "GhaK0w4S6Ieq5Yqo6aG+5a6i55Sf5oiQEi4KGFVubG9ja0Z1bmN0aW9uX0hv",
            "bWV3b3JsZBAJGhCK0w4M5a625Zut5YWl5Y+jEi4KGFVubG9ja0Z1bmN0aW9u",
            "X0RhaWx5VGFzaxAKGhCK0w4M5q+P5pel5Lu75YqhEioKGVVubG9ja0Z1bmN0",
            "aW9uX0Zsb3dlcmJlZDEQCxoLitMOB+iKseWcgzESKgoZVW5sb2NrRnVuY3Rp",
            "b25fRmxvd2VyYmVkMhAMGguK0w4H6Iqx5ZyDMhIqChlVbmxvY2tGdW5jdGlv",
            "bl9GbG93ZXJiZWQzEA0aC4rTDgfoirHlnIMzEioKGVVubG9ja0Z1bmN0aW9u",
            "X0Zsb3dlcmJlZDQQDhoLitMOB+iKseWcgzQSKAoSVW5sb2NrRnVuY3Rpb25f",
            "UGV0EA8aEIrTDgzlrqDnianlip/og70SIwoTVW5sb2NrRnVuY3Rpb25fRmlz",
            "aBAQGgqK0w4G6ZKT6bG8Ei4KGFVubG9ja0Z1bmN0aW9uX1Nob3BDbG9zZRAR",
            "GhCK0w4M5bqX6ZO65YWz6ZetEioKF1VubG9ja0Z1bmN0aW9uX0dpZnRDb2Rl",
            "EBQaDYrTDgnnpLzljIXnoIESKgoaVW5sb2NrRnVuY3Rpb25fQWNoaWV2ZW1l",
            "bnQQFRoKitMOBuaIkOWwsRIwChdVbmxvY2tGdW5jdGlvbl9Ib21lTW9yZRAW",
            "GhOK0w4P6aaW6aG15L6n6L655qCPEi0KF1VubG9ja0Z1bmN0aW9uX1JvdWxl",
            "dHRlEBcaEIrTDgzlubjov5Dovaznm5gSKwoVVW5sb2NrRnVuY3Rpb25fU2ln",
            "bkluEBgaEIrTDgzkuIPml6Xnrb7liLASJQoUVW5sb2NrRnVuY3Rpb25fSG9t",
            "ZTIQGRoLitMOB+WcuuaZrzISMQobVW5sb2NrRnVuY3Rpb25fR3Vlc3RDb2xs",
            "ZWN0EBoaEIrTDgzpob7lrqLlm77pibQSQgogVW5sb2NrRnVuY3Rpb25fRGVs",
            "ZXRlR3Vlc3RFZmZlY3QQGxocitMOGOaLieWuouWinuW8uueJueaViOWIoOmZ",
            "pBIvChlVbmxvY2tGdW5jdGlvbl9EZWNvcmF0aW9uEB0aEIrTDgzmvqHloILl",
            "vaLosaFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tsv2PbReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RES.ItemType), typeof(global::RES.UnlockFunction), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RES.ResReward), global::RES.ResReward.Parser, new[]{ "weight", "type", "proportion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ItemType {
    [pbr::OriginalName("ItemType_invalid")] Invalid = 0,
    [pbr::OriginalName("ItemType_coin")] Coin = 1,
    [pbr::OriginalName("ItemType_diamond")] Diamond = 2,
    [pbr::OriginalName("ItemType_exp")] Exp = 3,
    [pbr::OriginalName("ItemType_enenry")] Enenry = 4,
    [pbr::OriginalName("ItemType_achievement_point")] AchievementPoint = 5,
    [pbr::OriginalName("ItemType_fish")] Fish = 6,
    [pbr::OriginalName("ItemType_flower")] Flower = 7,
  }

  public enum UnlockFunction {
    [pbr::OriginalName("UnlockFunction_Invalid")] Invalid = 0,
    [pbr::OriginalName("UnlockFunction_Task")] Task = 1,
    [pbr::OriginalName("UnlockFunction_FreeDiamond")] FreeDiamond = 2,
    [pbr::OriginalName("UnlockFunction_FreeBox")] FreeBox = 3,
    [pbr::OriginalName("UnlockFunction_FreeGift")] FreeGift = 4,
    [pbr::OriginalName("UnlockFunction_RemoveClerk")] RemoveClerk = 5,
    [pbr::OriginalName("UnlockFunction_WeakTip")] WeakTip = 6,
    [pbr::OriginalName("UnlockFunction_VipGame")] VipGame = 7,
    [pbr::OriginalName("UnlockFunction_AutoGuest")] AutoGuest = 8,
    [pbr::OriginalName("UnlockFunction_Homeworld")] Homeworld = 9,
    [pbr::OriginalName("UnlockFunction_DailyTask")] DailyTask = 10,
    [pbr::OriginalName("UnlockFunction_Flowerbed1")] Flowerbed1 = 11,
    [pbr::OriginalName("UnlockFunction_Flowerbed2")] Flowerbed2 = 12,
    [pbr::OriginalName("UnlockFunction_Flowerbed3")] Flowerbed3 = 13,
    [pbr::OriginalName("UnlockFunction_Flowerbed4")] Flowerbed4 = 14,
    [pbr::OriginalName("UnlockFunction_Pet")] Pet = 15,
    [pbr::OriginalName("UnlockFunction_Fish")] Fish = 16,
    [pbr::OriginalName("UnlockFunction_ShopClose")] ShopClose = 17,
    [pbr::OriginalName("UnlockFunction_GiftCode")] GiftCode = 20,
    [pbr::OriginalName("UnlockFunction_Achievement")] Achievement = 21,
    [pbr::OriginalName("UnlockFunction_HomeMore")] HomeMore = 22,
    [pbr::OriginalName("UnlockFunction_Roulette")] Roulette = 23,
    [pbr::OriginalName("UnlockFunction_SignIn")] SignIn = 24,
    [pbr::OriginalName("UnlockFunction_Home2")] Home2 = 25,
    [pbr::OriginalName("UnlockFunction_GuestCollect")] GuestCollect = 26,
    [pbr::OriginalName("UnlockFunction_DeleteGuestEffect")] DeleteGuestEffect = 27,
    [pbr::OriginalName("UnlockFunction_Decoration")] Decoration = 29,
  }

  #endregion

  #region Messages
  public sealed partial class ResReward : pb::IMessage<ResReward>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResReward> _parser = new pb::MessageParser<ResReward>(() => new ResReward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResReward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RES.KeywordsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResReward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResReward(ResReward other) : this() {
      weight_ = other.weight_;
      type_ = other.type_;
      proportion_ = other.proportion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResReward Clone() {
      return new ResReward(this);
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int weightFieldNumber = 1;
    private int weight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int typeFieldNumber = 2;
    private global::RES.ItemType type_ = global::RES.ItemType.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RES.ItemType type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "proportion" field.</summary>
    public const int proportionFieldNumber = 3;
    private int proportion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int proportion {
      get { return proportion_; }
      set {
        proportion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResReward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResReward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (weight != other.weight) return false;
      if (type != other.type) return false;
      if (proportion != other.proportion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (weight != 0) hash ^= weight.GetHashCode();
      if (type != global::RES.ItemType.Invalid) hash ^= type.GetHashCode();
      if (proportion != 0) hash ^= proportion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (weight != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(weight);
      }
      if (type != global::RES.ItemType.Invalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) type);
      }
      if (proportion != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(proportion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (weight != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(weight);
      }
      if (type != global::RES.ItemType.Invalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) type);
      }
      if (proportion != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(proportion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (weight != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(weight);
      }
      if (type != global::RES.ItemType.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) type);
      }
      if (proportion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(proportion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResReward other) {
      if (other == null) {
        return;
      }
      if (other.weight != 0) {
        weight = other.weight;
      }
      if (other.type != global::RES.ItemType.Invalid) {
        type = other.type;
      }
      if (other.proportion != 0) {
        proportion = other.proportion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            weight = input.ReadInt32();
            break;
          }
          case 16: {
            type = (global::RES.ItemType) input.ReadEnum();
            break;
          }
          case 24: {
            proportion = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            weight = input.ReadInt32();
            break;
          }
          case 16: {
            type = (global::RES.ItemType) input.ReadEnum();
            break;
          }
          case 24: {
            proportion = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
