// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: keywords_client.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RES {

  /// <summary>Holder for reflection information generated from keywords_client.proto</summary>
  public static partial class KeywordsClientReflection {

    #region Descriptor
    /// <summary>File descriptor for keywords_client.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KeywordsClientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVrZXl3b3Jkc19jbGllbnQucHJvdG8SA1JFUxoMdHN2MnBiLnByb3RvGg5r",
            "ZXl3b3Jkcy5wcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tsv2PbReflection.Descriptor, global::RES.KeywordsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
