// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tsv2pb.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from tsv2pb.proto</summary>
public static partial class Tsv2PbReflection {

  #region Descriptor
  /// <summary>File descriptor for tsv2pb.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Tsv2PbReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgx0c3YycGIucHJvdG8aIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnBy",
          "b3RvOi0KBWZpZWxkEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxiR",
          "TiABKAk6MgoHbWFwcGluZxIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0",
          "aW9ucxihnAEgASgJOjQKCW1lcmdlX2tleRIfLmdvb2dsZS5wcm90b2J1Zi5N",
          "ZXNzYWdlT3B0aW9ucxiinAEgASgJOjEKBG5hbWUSIS5nb29nbGUucHJvdG9i",
          "dWYuRW51bVZhbHVlT3B0aW9ucxix6gEgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { Tsv2PbExtensions.field, Tsv2PbExtensions.mapping, Tsv2PbExtensions.merge_key, Tsv2PbExtensions.name }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of tsv2pb.proto</summary>
public static partial class Tsv2PbExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> field =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(10001, pb::FieldCodec.ForString(80010, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> mapping =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(20001, pb::FieldCodec.ForString(160010, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> merge_key =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(20002, pb::FieldCodec.ForString(160018, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> name =
    new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(30001, pb::FieldCodec.ForString(240010, ""));
}


#endregion Designer generated code
