// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keywords.proto

#include "keywords.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace RES {
constexpr ResReward::ResReward(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : weight_(0)
  , type_(0)

  , proportion_(0){}
struct ResRewardDefaultTypeInternal {
  constexpr ResRewardDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ResRewardDefaultTypeInternal() {}
  union {
    ResReward _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ResRewardDefaultTypeInternal _ResReward_default_instance_;
}  // namespace RES
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_keywords_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_keywords_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_keywords_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_keywords_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RES::ResReward, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RES::ResReward, weight_),
  PROTOBUF_FIELD_OFFSET(::RES::ResReward, type_),
  PROTOBUF_FIELD_OFFSET(::RES::ResReward, proportion_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::RES::ResReward)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::RES::_ResReward_default_instance_),
};

const char descriptor_table_protodef_keywords_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016keywords.proto\022\003RES\032\014tsv2pb.proto\"p\n\tR"
  "esReward\022\032\n\006weight\030\001 \001(\005B\n\212\361\004\006\346\235\203\351\207\215\022\'\n\004"
  "type\030\002 \001(\0162\r.RES.ItemTypeB\n\212\361\004\006\347\261\273\345\236\213\022\036\n"
  "\nproportion\030\003 \001(\005B\n\212\361\004\006\346\257\224\344\276\213*\211\002\n\010ItemTy"
  "pe\022\024\n\020ItemType_invalid\020\000\022\035\n\rItemType_coi"
  "n\020\001\032\n\212\323\016\006\351\222\236\347\245\250\022 \n\020ItemType_diamond\020\002\032\n\212"
  "\323\016\006\351\222\273\347\237\263\022\034\n\014ItemType_exp\020\003\032\n\212\323\016\006\347\273\217\351\252\214\022"
  "\037\n\017ItemType_enenry\020\004\032\n\212\323\016\006\344\275\223\345\212\233\022-\n\032Item"
  "Type_achievement_point\020\005\032\r\212\323\016\t\346\210\220\345\260\261\347\202\271\022"
  "\032\n\rItemType_fish\020\006\032\007\212\323\016\003\351\261\274\022\034\n\017ItemType_"
  "flower\020\007\032\007\212\323\016\003\350\212\261*\342\t\n\016UnlockFunction\022\032\n\026"
  "UnlockFunction_Invalid\020\000\022#\n\023UnlockFuncti"
  "on_Task\020\001\032\n\212\323\016\006\344\273\273\345\212\241\0220\n\032UnlockFunction_"
  "FreeDiamond\020\002\032\020\212\323\016\014\345\205\215\350\264\271\351\222\273\347\237\263\022,\n\026Unloc"
  "kFunction_FreeBox\020\003\032\020\212\323\016\014\345\205\215\350\264\271\345\256\235\347\256\261\022-\n"
  "\027UnlockFunction_FreeGift\020\004\032\020\212\323\016\014\345\205\215\350\264\271\347\244"
  "\274\345\214\205\0220\n\032UnlockFunction_RemoveClerk\020\005\032\020\212\323"
  "\016\014\346\222\244\344\270\213\345\221\230\345\267\245\022)\n\026UnlockFunction_WeakTip"
  "\020\006\032\r\212\323\016\t\345\260\217\345\212\251\346\211\213\022)\n\026UnlockFunction_VipG"
  "ame\020\007\032\r\212\323\016\t\345\260\217\346\270\270\346\210\217\0224\n\030UnlockFunction_A"
  "utoGuest\020\010\032\026\212\323\016\022\350\207\252\345\212\250\351\241\276\345\256\242\347\224\237\346\210\220\022.\n\030Un"
  "lockFunction_Homeworld\020\t\032\020\212\323\016\014\345\256\266\345\233\255\345\205\245\345"
  "\217\243\022.\n\030UnlockFunction_DailyTask\020\n\032\020\212\323\016\014\346\257"
  "\217\346\227\245\344\273\273\345\212\241\022*\n\031UnlockFunction_Flowerbed1\020"
  "\013\032\013\212\323\016\007\350\212\261\345\234\2031\022*\n\031UnlockFunction_Flowerb"
  "ed2\020\014\032\013\212\323\016\007\350\212\261\345\234\2032\022*\n\031UnlockFunction_Flo"
  "werbed3\020\r\032\013\212\323\016\007\350\212\261\345\234\2033\022*\n\031UnlockFunction"
  "_Flowerbed4\020\016\032\013\212\323\016\007\350\212\261\345\234\2034\022(\n\022UnlockFunc"
  "tion_Pet\020\017\032\020\212\323\016\014\345\256\240\347\211\251\345\212\237\350\203\275\022#\n\023UnlockFu"
  "nction_Fish\020\020\032\n\212\323\016\006\351\222\223\351\261\274\022.\n\030UnlockFunct"
  "ion_ShopClose\020\021\032\020\212\323\016\014\345\272\227\351\223\272\345\205\263\351\227\255\022*\n\027Unl"
  "ockFunction_GiftCode\020\024\032\r\212\323\016\t\347\244\274\345\214\205\347\240\201\022*\n"
  "\032UnlockFunction_Achievement\020\025\032\n\212\323\016\006\346\210\220\345\260"
  "\261\0220\n\027UnlockFunction_HomeMore\020\026\032\023\212\323\016\017\351\246\226\351"
  "\241\265\344\276\247\350\276\271\346\240\217\022-\n\027UnlockFunction_Roulette\020\027"
  "\032\020\212\323\016\014\345\271\270\350\277\220\350\275\254\347\233\230\022+\n\025UnlockFunction_Sig"
  "nIn\020\030\032\020\212\323\016\014\344\270\203\346\227\245\347\255\276\345\210\260\022%\n\024UnlockFunctio"
  "n_Home2\020\031\032\013\212\323\016\007\345\234\272\346\231\2572\0221\n\033UnlockFunction"
  "_GuestCollect\020\032\032\020\212\323\016\014\351\241\276\345\256\242\345\233\276\351\211\264\022B\n Unl"
  "ockFunction_DeleteGuestEffect\020\033\032\034\212\323\016\030\346\213\211"
  "\345\256\242\345\242\236\345\274\272\347\211\271\346\225\210\345\210\240\351\231\244\022/\n\031UnlockFunction_"
  "Decoration\020\035\032\020\212\323\016\014\346\276\241\345\240\202\345\275\242\350\261\241b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_keywords_2eproto_deps[1] = {
  &::descriptor_table_tsv2pb_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_keywords_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_keywords_2eproto = {
  false, false, 1678, descriptor_table_protodef_keywords_2eproto, "keywords.proto", 
  &descriptor_table_keywords_2eproto_once, descriptor_table_keywords_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_keywords_2eproto::offsets,
  file_level_metadata_keywords_2eproto, file_level_enum_descriptors_keywords_2eproto, file_level_service_descriptors_keywords_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_keywords_2eproto_getter() {
  return &descriptor_table_keywords_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_keywords_2eproto(&descriptor_table_keywords_2eproto);
namespace RES {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_keywords_2eproto);
  return file_level_enum_descriptors_keywords_2eproto[0];
}
bool ItemType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UnlockFunction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_keywords_2eproto);
  return file_level_enum_descriptors_keywords_2eproto[1];
}
bool UnlockFunction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 29:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ResReward::_Internal {
 public:
};

ResReward::ResReward(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:RES.ResReward)
}
ResReward::ResReward(const ResReward& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&weight_, &from.weight_,
    static_cast<size_t>(reinterpret_cast<char*>(&proportion_) -
    reinterpret_cast<char*>(&weight_)) + sizeof(proportion_));
  // @@protoc_insertion_point(copy_constructor:RES.ResReward)
}

void ResReward::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&weight_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&proportion_) -
    reinterpret_cast<char*>(&weight_)) + sizeof(proportion_));
}

ResReward::~ResReward() {
  // @@protoc_insertion_point(destructor:RES.ResReward)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ResReward::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ResReward::ArenaDtor(void* object) {
  ResReward* _this = reinterpret_cast< ResReward* >(object);
  (void)_this;
}
void ResReward::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ResReward::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ResReward::Clear() {
// @@protoc_insertion_point(message_clear_start:RES.ResReward)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&weight_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&proportion_) -
      reinterpret_cast<char*>(&weight_)) + sizeof(proportion_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResReward::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 weight = 1 [(.field) = "\346\235\203\351\207\215"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          weight_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .RES.ItemType type = 2 [(.field) = "\347\261\273\345\236\213"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::RES::ItemType>(val));
        } else goto handle_unusual;
        continue;
      // int32 proportion = 3 [(.field) = "\346\257\224\344\276\213"];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          proportion_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResReward::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RES.ResReward)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 weight = 1 [(.field) = "\346\235\203\351\207\215"];
  if (this->weight() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_weight(), target);
  }

  // .RES.ItemType type = 2 [(.field) = "\347\261\273\345\236\213"];
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // int32 proportion = 3 [(.field) = "\346\257\224\344\276\213"];
  if (this->proportion() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_proportion(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RES.ResReward)
  return target;
}

size_t ResReward::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RES.ResReward)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 weight = 1 [(.field) = "\346\235\203\351\207\215"];
  if (this->weight() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_weight());
  }

  // .RES.ItemType type = 2 [(.field) = "\347\261\273\345\236\213"];
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  // int32 proportion = 3 [(.field) = "\346\257\224\344\276\213"];
  if (this->proportion() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_proportion());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResReward::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RES.ResReward)
  GOOGLE_DCHECK_NE(&from, this);
  const ResReward* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResReward>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RES.ResReward)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RES.ResReward)
    MergeFrom(*source);
  }
}

void ResReward::MergeFrom(const ResReward& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RES.ResReward)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.weight() != 0) {
    _internal_set_weight(from._internal_weight());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.proportion() != 0) {
    _internal_set_proportion(from._internal_proportion());
  }
}

void ResReward::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RES.ResReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResReward::CopyFrom(const ResReward& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RES.ResReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResReward::IsInitialized() const {
  return true;
}

void ResReward::InternalSwap(ResReward* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResReward, proportion_)
      + sizeof(ResReward::proportion_)
      - PROTOBUF_FIELD_OFFSET(ResReward, weight_)>(
          reinterpret_cast<char*>(&weight_),
          reinterpret_cast<char*>(&other->weight_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ResReward::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_keywords_2eproto_getter, &descriptor_table_keywords_2eproto_once,
      file_level_metadata_keywords_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace RES
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::RES::ResReward* Arena::CreateMaybeMessage< ::RES::ResReward >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RES::ResReward >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
