// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from error_code.proto</summary>
public static partial class ErrorCodeReflection {

  #region Descriptor
  /// <summary>File descriptor for error_code.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorCodeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBlcnJvcl9jb2RlLnByb3RvKoMGCgxSZXRFcnJvckNvZGUSCgoGUkVUX09L",
          "EAASGgoWUkVUX1NFUlZFUl9JTk5FUl9FUlJPUhABEhsKF1JFVF9TRVJWRVJf",
          "UEFSQU1TX0VSUk9SEAISEAoMUkVUX0dNX0VSUk9SEAoSFAoQUkVUX0dNX0NN",
          "RF9FUlJPUhALEiAKHFJFVF9DVVJSRU5DWV9DT0lOX05PVF9FTk9VR0gQZBIj",
          "Ch9SRVRfQ1VSUkVOQ1lfRElBTU9ORF9OT1RfRU5PVUdIEGUSIgoeUkVUX0NV",
          "UlJFTkNZX0VORVJHWV9OT1RfRU5PVUdIEGYSJwojUkVUX0hPTUVXT1JMRF9G",
          "SVNIX1RJTUVTX05PVF9FTk9VR0gQbhIlCiFSRVRfSE9NRVdPUkxEX01PRFVM",
          "RV9MRVZFTF9JU19NQVgQbxIbChdSRVRfSE9NRVdPUkxEX01BWF9TVE9SRRBw",
          "EiEKHVJFVF9IT01FV09STERfU0FMRV9OT1RfRU5PVUdIEHESHAoYUkVUX0hP",
          "TUVXT1JMRF9GSVNIX0FEX0NEEHISHgoaUkVUX0hPTUVXT1JMRF9DQVRfTk9U",
          "X0lETEUQcxIgChxSRVRfSE9NRVdPUkxEX0NBVF9OT1RfR09IT01FEHQSFAoQ",
          "UkVUX1NIT1BTS0lMTF9DRBB4EhsKF1JFVF9TSE9QX1NLSUxMX05PX0dVRVNU",
          "EHkSFQoRUkVUX1NIT1BfTk9fQ0xFUksQehITCg9SRVRfU0hPUF9OT19GSVQQ",
          "exIRCg1SRVRfU0hPUF9MT0NLEHwSEgoOUkVUX1NIT1BfQ0xPU0UQfRIPCgtS",
          "RVRfU0hPUF9OTxB+EhMKD1JFVF9TSE9QX1JFUEFJUhB/EhYKEVJFVF9TSE9Q",
          "X0JVSUxESU5HEIABEhIKDVJFVF9TSE9QX0ZVTEwQgQESFQoQUkVUX1NIT1Bf",
          "Tk9fU0xPVBCCARIaChVSRVRfU0hPUF9XUk9OR19TVEFUVVMQgwESIAobUkVU",
          "X0dVRVNUQ09MTEVDVF9SRVdBUkRfR09UEIwBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RetErrorCode), }, null, null));
  }
  #endregion

}
#region Enums
public enum RetErrorCode {
  [pbr::OriginalName("RET_OK")] RetOk = 0,
  [pbr::OriginalName("RET_SERVER_INNER_ERROR")] RetServerInnerError = 1,
  /// <summary>
  /// 服务器参数错误
  /// </summary>
  [pbr::OriginalName("RET_SERVER_PARAMS_ERROR")] RetServerParamsError = 2,
  /// <summary>
  /// GM指令无效
  /// </summary>
  [pbr::OriginalName("RET_GM_ERROR")] RetGmError = 10,
  /// <summary>
  /// GM指令参数错误
  /// </summary>
  [pbr::OriginalName("RET_GM_CMD_ERROR")] RetGmCmdError = 11,
  /// <summary>
  /// 金币不足
  /// </summary>
  [pbr::OriginalName("RET_CURRENCY_COIN_NOT_ENOUGH")] RetCurrencyCoinNotEnough = 100,
  /// <summary>
  /// 钻石不足
  /// </summary>
  [pbr::OriginalName("RET_CURRENCY_DIAMOND_NOT_ENOUGH")] RetCurrencyDiamondNotEnough = 101,
  /// <summary>
  /// 体力不足
  /// </summary>
  [pbr::OriginalName("RET_CURRENCY_ENERGY_NOT_ENOUGH")] RetCurrencyEnergyNotEnough = 102,
  /// <summary>
  /// 家园-START
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_FISH_TIMES_NOT_ENOUGH")] RetHomeworldFishTimesNotEnough = 110,
  /// <summary>
  /// 模块已达等级上限
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_MODULE_LEVEL_IS_MAX")] RetHomeworldModuleLevelIsMax = 111,
  /// <summary>
  /// 家园仓库已满
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_MAX_STORE")] RetHomeworldMaxStore = 112,
  /// <summary>
  /// 家园购买商品不足
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_SALE_NOT_ENOUGH")] RetHomeworldSaleNotEnough = 113,
  /// <summary>
  /// 钓鱼广告CD冷却中
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_FISH_AD_CD")] RetHomeworldFishAdCd = 114,
  /// <summary>
  /// 宠物还没有准备好
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_CAT_NOT_IDLE")] RetHomeworldCatNotIdle = 115,
  /// <summary>
  /// 宠物奖励领取失败
  /// </summary>
  [pbr::OriginalName("RET_HOMEWORLD_CAT_NOT_GOHOME")] RetHomeworldCatNotGohome = 116,
  /// <summary>
  /// 店铺-START
  /// </summary>
  [pbr::OriginalName("RET_SHOPSKILL_CD")] RetShopskillCd = 120,
  /// <summary>
  /// 顾客不存在
  /// </summary>
  [pbr::OriginalName("RET_SHOP_SKILL_NO_GUEST")] RetShopSkillNoGuest = 121,
  /// <summary>
  /// 员工不存在，自动补货失败
  /// </summary>
  [pbr::OriginalName("RET_SHOP_NO_CLERK")] RetShopNoClerk = 122,
  /// <summary>
  /// 店铺未装配
  /// </summary>
  [pbr::OriginalName("RET_SHOP_NO_FIT")] RetShopNoFit = 123,
  /// <summary>
  /// 店铺未解锁
  /// </summary>
  [pbr::OriginalName("RET_SHOP_LOCK")] RetShopLock = 124,
  /// <summary>
  /// 当前店铺已关闭
  /// </summary>
  [pbr::OriginalName("RET_SHOP_CLOSE")] RetShopClose = 125,
  /// <summary>
  /// 店铺不存在
  /// </summary>
  [pbr::OriginalName("RET_SHOP_NO")] RetShopNo = 126,
  /// <summary>
  /// 店铺正在装修
  /// </summary>
  [pbr::OriginalName("RET_SHOP_REPAIR")] RetShopRepair = 127,
  /// <summary>
  /// 店铺正在建造
  /// </summary>
  [pbr::OriginalName("RET_SHOP_BUILDING")] RetShopBuilding = 128,
  /// <summary>
  /// 客人已满，请扩建客人空间
  /// </summary>
  [pbr::OriginalName("RET_SHOP_FULL")] RetShopFull = 129,
  /// <summary>
  /// 没有槽位
  /// </summary>
  [pbr::OriginalName("RET_SHOP_NO_SLOT")] RetShopNoSlot = 130,
  /// <summary>
  /// 店铺状态错误
  /// </summary>
  [pbr::OriginalName("RET_SHOP_WRONG_STATUS")] RetShopWrongStatus = 131,
  /// <summary>
  /// 客人图鉴-START
  /// </summary>
  [pbr::OriginalName("RET_GUESTCOLLECT_REWARD_GOT")] RetGuestcollectRewardGot = 140,
}

#endregion


#endregion Designer generated code
