// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tsv2pb.proto

#include "tsv2pb.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_tsv2pb_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_tsv2pb_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_tsv2pb_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_tsv2pb_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014tsv2pb.proto\032 google/protobuf/descript"
  "or.proto:-\n\005field\022\035.google.protobuf.Fiel"
  "dOptions\030\221N \003(\t:2\n\007mapping\022\037.google.prot"
  "obuf.MessageOptions\030\241\234\001 \003(\t:4\n\tmerge_key"
  "\022\037.google.protobuf.MessageOptions\030\242\234\001 \001("
  "\t:1\n\004name\022!.google.protobuf.EnumValueOpt"
  "ions\030\261\352\001 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_tsv2pb_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_tsv2pb_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tsv2pb_2eproto = {
  false, false, 260, descriptor_table_protodef_tsv2pb_2eproto, "tsv2pb.proto", 
  &descriptor_table_tsv2pb_2eproto_once, descriptor_table_tsv2pb_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_tsv2pb_2eproto::offsets,
  nullptr, file_level_enum_descriptors_tsv2pb_2eproto, file_level_service_descriptors_tsv2pb_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_tsv2pb_2eproto_getter() {
  return &descriptor_table_tsv2pb_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_tsv2pb_2eproto(&descriptor_table_tsv2pb_2eproto);
const std::string field_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  field(kFieldFieldNumber, field_default);
const std::string mapping_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false >
  mapping(kMappingFieldNumber, mapping_default);
const std::string merge_key_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  merge_key(kMergeKeyFieldNumber, merge_key_default);
const std::string name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  name(kNameFieldNumber, name_default);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
